apiVersion: v1
kind: Pod
metadata:
  name: audiobookshelf
  labels:
    app: audiobookshelf
    servicebay.role: media
  annotations:
    servicebay.ports: "{{ABS_PORT}}/tcp"
spec:
  hostNetwork: true
  containers:
  - name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    env:
      - name: PORT
        value: "{{ABS_PORT}}"
      - name: TZ
        value: "{{TZ}}"
    ports:
      - containerPort: {{ABS_PORT}}
    volumeMounts:
      - mountPath: /config
        name: abs-config
      - mountPath: /metadata
        name: abs-metadata
      - mountPath: /audiobooks
        name: abs-audiobooks
      - mountPath: /podcasts
        name: abs-podcasts
  volumes:
  - name: abs-config
    hostPath:
      path: {{DATA_DIR}}/audiobookshelf/config
      type: DirectoryOrCreate
  - name: abs-metadata
    hostPath:
      path: {{DATA_DIR}}/audiobookshelf/metadata
      type: DirectoryOrCreate
  - name: abs-audiobooks
    hostPath:
      path: {{ABS_AUDIOBOOKS_PATH}}
      type: DirectoryOrCreate
  - name: abs-podcasts
    hostPath:
      path: {{ABS_PODCASTS_PATH}}
      type: DirectoryOrCreate
