/**
 * Reset preserve-group identifiers used by `/api/system/stacks/reset`
 * and `/api/system/stacks/reset/info`. The wizard surfaces a checkbox
 * per group so the operator can pick *what* a "clean install"
 * actually wipes (#568 transparency rework).
 *
 * Defaults preserve the three system-critical groups; only
 * `service-data` (app payload — photos, HA, media, …) wipes unless
 * the operator explicitly opts in. The previous behaviour was "wipe
 * everything" which caused the May-15 data-loss incident
 * (see [[feedback_destructive_install_options]]).
 *
 * Groups with `alwaysWipe: true` are listed for transparency but
 * cannot be preserved — e.g. `quadlet-backup` is recreated by
 * setup-raid.sh on next boot, so leaving stale units behind would
 * silently resurrect deleted services after an OS reinstall.
 *
 * Lives in /src/lib because Next.js route files cannot export extra
 * symbols — the route handler imports from here instead.
 */

export const RESET_GROUPS = {
  /** ServiceBay's own state: secret.key, .auth-secret.env, config.json,
   *  cert-archive. Wiping this turns every `enc:v1:` encrypted credential
   *  in config.json into garbage (the AES key + AUTH_SECRET are here).
   *  Default: PRESERVE. */
  secrets: {
    paths: ['/var/mnt/data/servicebay'],
    label: 'ServiceBay secrets + config',
    description: 'Encryption keys (secret.key, AUTH_SECRET), config.json, cert-archive. Wiping these forces every encrypted credential to be re-entered and the wizard to start over.',
  },
  /** NPM proxy + LE certs as a unit. Cert-reuse logic (#566) needs
   *  both the on-disk certs AND NPM's DB rows that reference them by
   *  id, so we treat them atomically.
   *  Default: PRESERVE — LE has a 5-duplicate-certs / 168h rate limit
   *  that bites if you wipe + re-issue more than a couple of times. */
  certs: {
    paths: ['/var/mnt/data/stacks/nginx-proxy-manager'],
    label: 'NPM proxy + Let\'s Encrypt certs',
    description: 'Reverse-proxy config + issued LE certificates. Wiping triggers fresh ACME challenges on next install — LE\'s rate limit blocks repeated wipes.',
  },
  /** Authelia + LLDAP — identity provider state. Wiping means
   *  re-seeding users, regenerating OIDC client secrets, and every
   *  SSO-enabled service has to be re-linked.
   *  Default: PRESERVE. */
  identity: {
    paths: ['/var/mnt/data/stacks/auth'],
    label: 'Identity provider (Authelia + LLDAP)',
    description: 'User accounts, groups, OIDC clients, session cookies. Wiping means every family member re-creates their login and every SSO-enabled service re-pairs.',
  },
  /** Everything else under stacks/*: photos, music, HA configs,
   *  Vaultwarden vault, Syncthing config, AdGuard rules, …
   *  Default: WIPE. The "clean" in clean install. */
  'service-data': {
    paths: ['/var/mnt/data/stacks'],
    label: 'Service data (photos, HA, media, files, vault, …)',
    description: 'Immich photos, Home Assistant configs, media library, Vaultwarden vault, Syncthing data, AdGuard rules, etc. The "clean" in clean install.',
  },
  /** Snapshot of generated systemd Quadlet units that setup-raid.sh
   *  recreates on next boot. Always wiped: leaving it behind would
   *  silently resurrect deleted services after an OS reinstall.
   *  Listed as its own group so the UI can show its size honestly —
   *  on a long-lived node this is often ~800 MB and used to be
   *  counted (incorrectly) under `secrets`. */
  'quadlet-backup': {
    paths: ['/var/mnt/data/servicebay/quadlet-backup'],
    label: 'Quadlet unit backup',
    description: 'Snapshot of systemd Quadlet units regenerated by setup-raid.sh on next boot. Always wiped during clean install so an OS reinstall does not restore stale units.',
    alwaysWipe: true,
  },
} as const;

export type ResetGroup = keyof typeof RESET_GROUPS;

/** Default `preserve` array when the API caller omits one. Keeps the
 *  three system-critical groups; only `service-data` wipes (and
 *  `quadlet-backup` which is alwaysWipe). */
export const DEFAULT_PRESERVE: ResetGroup[] = ['secrets', 'certs', 'identity'];

/** True when the group ignores the preserve list and is wiped
 *  unconditionally. The UI renders these as disabled rows so the
 *  operator sees the size but cannot toggle them. */
export function isAlwaysWipe(group: ResetGroup): boolean {
  const def = RESET_GROUPS[group] as { alwaysWipe?: boolean };
  return def.alwaysWipe === true;
}

/** Direct-child basenames inside `group`'s paths that belong to
 *  *other* declared groups. Used by both `du` (so per-group sizes
 *  don't double-count) and the wipe step (so a `find ... rm -rf` on
 *  a parent dir skips children that are accounted for separately).
 *
 *  Derived from the path topology so adding/renaming a group can't
 *  drift out of sync with a hand-maintained exclusion list. */
export function getChildExclusions(group: ResetGroup): string[] {
  const myPaths = RESET_GROUPS[group].paths.map(stripTrailingSlash);
  const excluded: string[] = [];
  for (const other of Object.keys(RESET_GROUPS) as ResetGroup[]) {
    if (other === group) continue;
    for (const p of RESET_GROUPS[other].paths) {
      const norm = stripTrailingSlash(p);
      const parent = myPaths.find(mp => norm.startsWith(mp + '/'));
      if (!parent) continue;
      const rest = norm.slice(parent.length + 1);
      // Only direct children — deeper paths can't be excluded by basename.
      if (!rest.includes('/')) excluded.push(rest);
    }
  }
  return excluded;
}

function stripTrailingSlash(p: string): string {
  return p.endsWith('/') && p.length > 1 ? p.slice(0, -1) : p;
}
