apiVersion: v1
kind: Pod
metadata:
  name: immich
  labels:
    app: immich
spec:
  containers:
    - name: immich-server
      image: ghcr.io/immich-app/immich-server:release
      args: ["start-server.sh"]
      env:
        - name: DB_HOSTNAME
          value: "localhost"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_DATABASE_NAME
          value: "immich"
        - name: REDIS_HOSTNAME
          value: "localhost"
        - name: IMMICH_MACHINE_LEARNING_URL
          value: "http://localhost:3003"
      ports:
        - containerPort: 2283
          hostPort: {{PORT}}
      volumeMounts:
        - mountPath: /usr/src/app/upload
          name: immich-upload
    
    - name: immich-microservices
      image: ghcr.io/immich-app/immich-server:release
      args: ["start-microservices.sh"]
      env:
        - name: DB_HOSTNAME
          value: "localhost"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_DATABASE_NAME
          value: "immich"
        - name: REDIS_HOSTNAME
          value: "localhost"
        - name: IMMICH_MACHINE_LEARNING_URL
          value: "http://localhost:3003"
      volumeMounts:
        - mountPath: /usr/src/app/upload
          name: immich-upload

    - name: immich-machine-learning
      image: ghcr.io/immich-app/immich-machine-learning:release
      volumeMounts:
        - mountPath: /cache
          name: model-cache

    - name: redis
      image: docker.io/redis:6.2-alpine

    - name: database
      image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
      env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "immich"
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata

  volumes:
    - name: immich-upload
      persistentVolumeClaim:
        claimName: immich-upload-pvc
    - name: model-cache
      persistentVolumeClaim:
        claimName: immich-model-cache-pvc
    - name: pgdata
      persistentVolumeClaim:
        claimName: immich-pgdata-pvc
