apiVersion: v1
kind: Stack
metadata:
  name: vaultwarden
  annotations:
    servicebay.label: "Vaultwarden (Passwords)"
    servicebay.tier: "feature"
    servicebay.depends-on-stacks: "basic"
spec:
  templates: [vaultwarden]
