apiVersion: v1
kind: Pod
metadata:
  name: nginx-web
  labels:
    app: nginx-web
spec:
  containers:
  - name: nginx
    image: docker.io/library/nginx:alpine
    ports:
    - containerPort: 80
      hostPort: {{PORT}}
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-data
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: nginx-data-pvc

