apiVersion: v1
kind: Pod
metadata:
  name: nginx-web
  labels:
    app: nginx-web
    servicebay.role: reverse-proxy
spec:
  containers:
  - name: nginx
    image: docker.io/library/nginx:alpine
    ports:
    - containerPort: 80
      hostPort: {{PORT}}
    - containerPort: 443
      hostPort: {{SSL_PORT}}
    volumeMounts:
    - mountPath: /etc/nginx/conf.d
      name: nginx-conf
    - mountPath: /etc/nginx/ssl
      name: nginx-ssl
    - mountPath: /usr/share/nginx/html
      name: nginx-data
  volumes:
  - name: nginx-conf
    hostPath:
      path: {{DATA_DIR}}/nginx/conf.d
      type: DirectoryOrCreate
  - name: nginx-ssl
    hostPath:
      path: {{DATA_DIR}}/nginx/ssl
      type: DirectoryOrCreate
  - name: nginx-data
    hostPath:
      path: {{DATA_DIR}}/nginx/html
      type: DirectoryOrCreate
