apiVersion: v1
kind: Pod
metadata:
  name: nginx-web
  labels:
    app: nginx-web
    servicebay.role: reverse-proxy
spec:
  containers:
  - name: nginx-proxy-manager
    image: docker.io/jc21/nginx-proxy-manager:latest
    ports:
    - containerPort: 80
      hostPort: {{PORT}}
    - containerPort: 443
      hostPort: {{SSL_PORT}}
    - containerPort: 81
      hostPort: {{ADMIN_PORT}}
    volumeMounts:
    - mountPath: /data
      name: npm-data
    - mountPath: /etc/letsencrypt
      name: npm-letsencrypt
  volumes:
  - name: npm-data
    hostPath:
      path: {{DATA_DIR}}/nginx-proxy-manager/data
      type: DirectoryOrCreate
  - name: npm-letsencrypt
    hostPath:
      path: {{DATA_DIR}}/nginx-proxy-manager/letsencrypt
      type: DirectoryOrCreate
