import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';

/**
 * Tests the encrypt/decrypt helpers and — critically — the new
 * key-mismatch behaviour from #780. The module reads `DATA_DIR` at
 * import time via `./dirs`, so each test resets the module cache
 * after pointing DATA_DIR at a fresh tmpdir.
 */

const ORIGINAL_DATA_DIR = process.env.DATA_DIR;

function freshDataDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sb-secrets-test-'));
  process.env.DATA_DIR = dir;
  return dir;
}

async function loadSecretsModule(): Promise<typeof import('./secrets')> {
  vi.resetModules();
  return await import('./secrets');
}

beforeEach(() => {
  process.env.DATA_DIR = ORIGINAL_DATA_DIR;
});

afterEach(() => {
  vi.restoreAllMocks();
  process.env.DATA_DIR = ORIGINAL_DATA_DIR;
});

describe('encrypt + decrypt round trip', () => {
  it('encrypts a plaintext into enc:v1: format and decrypts back to the same value', async () => {
    freshDataDir();
    const { encrypt, decrypt } = await loadSecretsModule();
    const sealed = encrypt('hunter2');
    expect(sealed.startsWith('enc:v1:')).toBe(true);
    expect(decrypt(sealed)).toBe('hunter2');
  });

  it('returns empty input verbatim (encrypt + decrypt)', async () => {
    freshDataDir();
    const { encrypt, decrypt } = await loadSecretsModule();
    expect(encrypt('')).toBe('');
    expect(decrypt('')).toBe('');
  });

  it('passes through non-prefixed plaintext on decrypt', async () => {
    freshDataDir();
    const { decrypt } = await loadSecretsModule();
    expect(decrypt('plain value')).toBe('plain value');
  });

  it('treats a malformed enc:… string (wrong segment count) as opaque', async () => {
    freshDataDir();
    const { decrypt } = await loadSecretsModule();
    // 4 parts instead of 5 — not "GCM failed", just "not our format"
    // Preserve verbatim so we don't silently nuke an operator-typed
    // value that happens to start with enc:
    expect(decrypt('enc:v1:ab:cd')).toBe('enc:v1:ab:cd');
  });
});

describe('decrypt key-mismatch behaviour (#780)', () => {
  it('returns empty string when the key on disk no longer matches the one used at encrypt time', async () => {
    // Step 1: encrypt with key A.
    const dirA = freshDataDir();
    const modA = await loadSecretsModule();
    const sealed = modA.encrypt('original password');
    expect(modA.decrypt(sealed)).toBe('original password');

    // Step 2: swap secret.key for a different one (simulates the
    // "secret.key regenerated by reinstall" scenario), reload module
    // to clear the cached buffer.
    const keyB = Buffer.alloc(32, 0x42);
    fs.writeFileSync(path.join(dirA, 'secret.key'), keyB);
    const modB = await loadSecretsModule();

    expect(modB.decrypt(sealed)).toBe('');
    expect(modB.hasDecryptMismatch()).toBe(true);
  });

  it('logs the mismatch warning only once per process', async () => {
    const dir = freshDataDir();
    const mod1 = await loadSecretsModule();
    const sealed = mod1.encrypt('secret1');

    fs.writeFileSync(path.join(dir, 'secret.key'), Buffer.alloc(32, 0xaa));
    const mod2 = await loadSecretsModule();
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => {});

    expect(mod2.decrypt(sealed)).toBe('');
    expect(mod2.decrypt(sealed)).toBe('');
    expect(mod2.decrypt(sealed)).toBe('');
    expect(warn).toHaveBeenCalledTimes(1);
    expect(warn.mock.calls[0][0]).toMatch(/secret\.key/);
  });

  it('hasDecryptMismatch stays false when every value decrypts cleanly', async () => {
    freshDataDir();
    const mod = await loadSecretsModule();
    mod.decrypt(mod.encrypt('a'));
    mod.decrypt(mod.encrypt('b'));
    mod.decrypt('not encrypted');
    mod.decrypt('');
    expect(mod.hasDecryptMismatch()).toBe(false);
  });
});

describe('secret.key file management', () => {
  it('creates secret.key with mode 0600 on first use', async () => {
    const dir = freshDataDir();
    const mod = await loadSecretsModule();
    mod.encrypt('trigger key creation');
    const stat = fs.statSync(path.join(dir, 'secret.key'));
    // Mask off file-type bits; compare permission bits.
    expect(stat.mode & 0o777).toBe(0o600);
    expect(stat.size).toBe(32);
  });

  it('reuses an existing secret.key instead of generating a fresh one', async () => {
    const dir = freshDataDir();
    const knownKey = Buffer.alloc(32, 0x37);
    fs.writeFileSync(path.join(dir, 'secret.key'), knownKey, { mode: 0o600 });

    const mod = await loadSecretsModule();
    mod.encrypt('anything');
    // File contents must be unchanged — the constructor should only
    // generate when missing.
    expect(fs.readFileSync(path.join(dir, 'secret.key'))).toEqual(knownKey);
  });
});
