import type { StorybookConfig } from '@storybook/nextjs';

/**
 * Storybook config for ServiceBay's frontend (Phase 4 of #753).
 *
 * Story discovery is scoped to `packages/frontend/src/**` so we
 * never accidentally pull a backend file into the client bundle.
 * Stories are co-located with their components (`Sidebar.stories.tsx`
 * sits next to `Sidebar.tsx`), matching the api-client → frontend
 * → backend boundary that the rest of the codebase enforces.
 *
 * The `nextjs` framework gives us:
 *   - Tailwind + global CSS via the same `next dev` resolution
 *   - `next/font` (Geist) without a babel hack
 *   - `next/image` mocked so stories don't 404 on missing assets
 *   - `@/` alias resolution via the package's own tsconfig
 */
const config: StorybookConfig = {
  stories: [
    '../packages/frontend/src/**/*.stories.@(ts|tsx)',
  ],
  addons: [
    // Core "essentials" (controls, actions, docs, viewport, …) are
    // built into Storybook 10. Only opt-in addons go here.
    // '@storybook/addon-onboarding',  // disabled — bring back when first-run wizard is needed
  ],
  framework: {
    name: '@storybook/nextjs',
    options: {
      // Path is resolved relative to this file by the framework.
      nextConfigPath: '../next.config.ts',
    },
  },
  staticDirs: [
    // The MSW service-worker file lives under packages/frontend/public/
    // (generated by `npx msw init`); mounting it at Storybook's root
    // lets msw-storybook-addon find it at `/mockServiceWorker.js`.
    '../packages/frontend/public',
  ],
  typescript: {
    // Default `react-docgen-typescript` is slow on a large project.
    // `react-docgen` is faster and good enough for our control-table
    // ergonomics; stories that need richer arg types can declare
    // them explicitly via the meta `argTypes` field.
    reactDocgen: 'react-docgen',
  },
};

export default config;
