apiVersion: v1
kind: Pod
metadata:
  name: redis-cache
  labels:
    app: redis-cache
spec:
  containers:
  - name: redis
    image: docker.io/library/redis:{{VERSION}}
    ports:
    - containerPort: 6379
      hostPort: 6379

