/**
 * Template manifest — single source of truth for what `template.yml`
 * may contain and which fields are required (#585).
 *
 * Until this module existed, the same regex pattern was duplicated in
 * four files (templateLabel.ts, templateTier.ts, templateSchemaVersion.ts,
 * stackInstall/dependencies.ts) and twice more inline in registry.ts,
 * each parsing one annotation. Build-time tests then re-asserted some
 * (but not all) of those rules with hand-rolled regexes of their own.
 * Adding a field meant editing five files plus two docs.
 *
 * This module unifies the parsing into one function and one field-spec
 * table that drives both runtime validation and the autogenerated
 * field-reference section in docs/TEMPLATE_AUTHORING.md.
 *
 * Adding a field:
 *   1. extend TemplateManifest below
 *   2. add a `TEMPLATE_FIELDS` entry with required/default/description
 *   3. extend parseTemplateManifest with the field's parsing rule
 *   4. run `npm run gen-template-docs` to refresh the docs table
 *
 * No client/server split: the parser is pure (no fs / Node deps) and is
 * safe to import from React components.
 */

import { type TemplateApiVersions, type TemplateApiName, SUPPORTED_API_VERSIONS } from './apiVersions';
import { parseReadinessYaml } from '@/lib/install/readiness/parse';

/** Recognized template tiers. `feature` is the implicit default. */
export type TemplateTier = 'infrastructure' | 'feature';
const KNOWN_TIERS: ReadonlySet<TemplateTier> = new Set(['infrastructure', 'feature']);

/** Parsed template metadata. Stable shape — both runtime + tests rely on it. */
export interface TemplateManifest {
  /** `metadata.annotations['servicebay.label']` — friendly UI label. Required. */
  label: string;
  /**
   * `metadata.annotations['servicebay.tier']`. `feature` is the implicit
   * default — anything not in KNOWN_TIERS is an error.
   */
  tier: TemplateTier;
  /**
   * `metadata.annotations['servicebay.schema-version']`. Positive integer.
   * Defaults to 1 when the annotation is missing.
   */
  schemaVersion: number;
  /**
   * `metadata.annotations['servicebay.dependencies']` — comma-separated
   * template names this template needs installed first. Empty array when
   * missing.
   */
  dependencies: string[];
  /**
   * `metadata.annotations['servicebay.config-mount']` — container mountPath
   * the wizard should write companion `*.mustache` files into. Required
   * only when the template ships `*.mustache` files (caller signals via
   * ParseContext.hasMustacheConfigs).
   */
  configMount?: string;
  /**
   * `metadata.annotations['servicebay.ports']` — comma-separated `port/proto`
   * list (e.g. `"8080/tcp,8443/tcp"`). Recommended; no validation beyond
   * "is a string" today.
   */
  ports?: string;
  /**
   * `metadata.annotations['servicebay.requires-api.<name>']` (#588).
   * Each declared key is the version of a ServiceBay-internal `/api/system/<name>/*`
   * surface the template's `post-deploy.py` calls. Core refuses to invoke
   * `post-deploy.py` if the template requests a version this core can't satisfy.
   * Empty / missing = template makes no such calls.
   */
  requiresApi?: TemplateApiVersions;
  /**
   * `metadata.annotations['servicebay.readiness']` (#613) — raw YAML body of
   * the readiness probe list. Stored unparsed here because the parser runs
   * twice over the template lifecycle:
   *   1. At lint/test time, on the pre-Mustache template, just to assert
   *      the structure is well-formed (with `{{VAR}}` placeholders left
   *      as opaque strings).
   *   2. At install time, on the Mustache-rendered body, to get the
   *      concrete probe values to execute.
   * `parseTemplateManifest` runs step 1 and surfaces structural errors;
   * the install runner runs step 2 and executes the probes.
   */
  readinessRaw?: string;
}

/** Context the caller can pass to enable conditional rules. */
export interface ParseContext {
  /** True if the template directory contains `*.mustache` companion config
   *  files. When set, `servicebay.config-mount` becomes required — without
   *  the annotation the resolver falls back to a `/config`-suffix heuristic
   *  that silently picks the wrong mount in multi-volume pods. */
  hasMustacheConfigs?: boolean;
}

export type ParseResult =
  | { ok: true; manifest: TemplateManifest; warnings: string[] }
  | { ok: false; errors: string[]; warnings: string[] };

/**
 * Field-spec table. Single source of truth for both parser behavior and
 * the autogenerated docs table. Order is the order entries appear in the
 * generated docs (most-important first).
 */
export interface TemplateFieldSpec {
  /** Annotation key inside `metadata.annotations`. */
  annotation: string;
  /** Manifest field name. */
  field: keyof TemplateManifest;
  /** `true` always required; `'if-mustache-configs'` required iff the
   *  template ships `*.mustache` files; `false` optional. */
  required: true | false | 'if-mustache-configs';
  /** Default applied when annotation is missing (and field is not required). */
  default?: string | number | string[];
  /** Enum of allowed values, if any. */
  validValues?: readonly string[];
  /** One-line description for the docs table. */
  description: string;
}

export const TEMPLATE_FIELDS: readonly TemplateFieldSpec[] = [
  {
    annotation: 'servicebay.label',
    field: 'label',
    required: true,
    description:
      'Friendly UI label shown in the wizard\'s configure step (e.g. `"Vaultwarden (Passwords)"`). ' +
      'Without it the section header falls back to the raw template name.',
  },
  {
    annotation: 'servicebay.ports',
    field: 'ports',
    required: false,
    description:
      'Comma-separated `port/proto` list (e.g. `"8080/tcp,8443/tcp"`). ' +
      'Drives gateway probes + the network graph.',
  },
  {
    annotation: 'servicebay.config-mount',
    field: 'configMount',
    required: 'if-mustache-configs',
    description:
      'Container mountPath that companion `*.mustache` files should land in. ' +
      'Avoids the `/config`-suffix heuristic picking the wrong volume in multi-container pods.',
  },
  {
    annotation: 'servicebay.schema-version',
    field: 'schemaVersion',
    required: false,
    default: 1,
    description:
      'Bump when the pod structure or variable shape changes in a way operators need to be aware of ' +
      '(containers extracted, variables renamed, data paths moved). Plain image-tag bumps don\'t need ' +
      'this — Quadlet\'s `AutoUpdate=registry` handles those silently. Each bump should ship a ' +
      '`CHANGELOG.md` section + (if data needs to move) a `migrations/v{N-1}-to-v{N}.py` script. See #352.',
  },
  {
    annotation: 'servicebay.tier',
    field: 'tier',
    required: false,
    default: 'feature',
    validValues: ['infrastructure', 'feature'],
    description:
      '`"infrastructure"` for platform templates that the wizard auto-includes (DNS / proxy / SSO) and ' +
      'pins checked; everything else defaults to `"feature"` and starts unchecked. Stacks don\'t carry ' +
      'this annotation.',
  },
  {
    annotation: 'servicebay.dependencies',
    field: 'dependencies',
    required: false,
    default: [],
    description:
      'Comma-separated list of template names that must install before this one. Drives three things ' +
      'in the wizard: (1) the red **`requires X`** badge under the template name; (2) auto-checking ' +
      'those templates when the operator checks this one; (3) the uncheck-guard that prompts before ' +
      'removing a template another selected template needs. The install loop then topo-sorts the ' +
      'deploy order so deps land first. Example: `servicebay.dependencies: "nginx,auth"`.',
  },
  {
    annotation: 'servicebay.requires-api.<name>',
    field: 'requiresApi',
    required: false,
    description:
      'Per-API version the template\'s `post-deploy.py` calls. Declare one annotation per API name (`lldap`, ' +
      '`authelia`, `portal`), value is a positive integer. Core refuses to invoke `post-deploy.py` if any ' +
      'requested version exceeds what this ServiceBay ships (see `src/lib/template/apiVersions.ts`). ' +
      'Use this on any template whose post-deploy calls `/api/system/<name>/*` (#588).',
  },
  {
    annotation: 'servicebay.readiness',
    field: 'readinessRaw',
    required: false,
    description:
      'YAML block scalar declaring readiness probes the install runner waits on after the unit starts and ' +
      'before invoking `post-deploy.py` (#613). Each probe is `{kind: http|tcp|ldap|command, ..., timeout: 60s}`. ' +
      'Replaces ad-hoc wait helpers (`wait_for_lldap`, `wait_pod_running`, …) with a uniform shape, same retry ' +
      'budget, and structured install-blocking error. Declare for any template another template lists in ' +
      '`servicebay.dependencies` — otherwise downstream post-deploys race the upstream container.',
  },
] as const;

/**
 * Pull a multi-line YAML block scalar (`key: |` or `key: >`) out of raw
 * template YAML. Indentation-anchored: captures every subsequent line
 * indented strictly more than the key line, stops at the first line that
 * dedents back to (or past) the key. Returns the block body with the
 * leading per-line indentation stripped — i.e. the raw YAML you'd feed
 * into a follow-up `yaml.load`.
 */
function readBlockScalarAnnotation(yamlText: string, annotation: string): string | undefined {
  const escaped = annotation.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const headerRe = new RegExp(`^(\\s+)${escaped}:\\s*([|>])[+-]?\\s*$`, 'm');
  const header = headerRe.exec(yamlText);
  if (!header) return undefined;
  const keyIndent = header[1].length;
  const afterHeader = yamlText.slice(header.index + header[0].length);
  const lines = afterHeader.split('\n');
  // First line after the header is the start of the block; consume lines
  // indented strictly deeper than the key. A blank line is part of the
  // block if the next non-blank line is still indented.
  const blockLines: string[] = [];
  let blockIndent: number | null = null;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === '') { blockLines.push(''); continue; }
    const indent = line.length - line.trimStart().length;
    if (indent <= keyIndent) break;
    if (blockIndent === null) blockIndent = indent;
    blockLines.push(line.slice(Math.min(indent, blockIndent)));
  }
  // Trim trailing blank lines that aren't part of any indented content.
  while (blockLines.length > 0 && blockLines[blockLines.length - 1].trim() === '') {
    blockLines.pop();
  }
  if (blockLines.length === 0) return undefined;
  return blockLines.join('\n') + '\n';
}

/**
 * Pull a single annotation value out of raw YAML text. Regex-based on
 * purpose: this function runs against pre-mustache-substitution YAML
 * (the wizard collects variables before render), and our templates
 * contain `{{PLACEHOLDER}}` strings that pass js-yaml's parser
 * incidentally — we don't want to depend on that. Annotation values
 * themselves are always literal strings in our templates.
 *
 * Matches `key: "..."`, `key: '...'`, or `key: bare value` (until end
 * of line). Anchored to an annotation-style indented line so it doesn't
 * latch onto references inside multi-line scalars or comments.
 */
function readAnnotation(yamlText: string, annotation: string): string | undefined {
  // Escape regex metacharacters in the annotation key (the `.` in
  // `servicebay.label` would otherwise match anything).
  const escaped = annotation.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(
    `^\\s+${escaped}:\\s*(?:"([^"]*)"|'([^']*)'|([^\\n#]+?))\\s*$`,
    'm',
  );
  const m = re.exec(yamlText);
  if (!m) return undefined;
  const raw = (m[1] ?? m[2] ?? m[3] ?? '').trim();
  return raw === '' ? undefined : raw;
}

/**
 * Parse a template.yml's manifest annotations. Pure function — caller
 * passes the YAML text plus optional context flags. Returns either a
 * complete manifest or a list of human-readable errors.
 */
export function parseTemplateManifest(
  yamlText: string,
  ctx: ParseContext = {},
): ParseResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  const label = readAnnotation(yamlText, 'servicebay.label');
  if (label === undefined) {
    errors.push(
      'Missing required annotation `servicebay.label`. Add it under `metadata.annotations` ' +
      'with a friendly display name (e.g. `servicebay.label: "Vaultwarden (Passwords)"`).',
    );
  }

  const ports = readAnnotation(yamlText, 'servicebay.ports');

  const configMount = readAnnotation(yamlText, 'servicebay.config-mount');
  if (ctx.hasMustacheConfigs && !configMount) {
    errors.push(
      'Template ships *.mustache config files but has no `servicebay.config-mount` annotation. ' +
      'Without it the resolver falls back to a `/config`-suffix heuristic that silently picks the ' +
      'wrong mount in multi-volume pods. Add `servicebay.config-mount: "<container mountPath>"` ' +
      'pointing at the volume the configs should land in.',
    );
  }

  let schemaVersion = 1;
  const schemaRaw = readAnnotation(yamlText, 'servicebay.schema-version');
  if (schemaRaw !== undefined) {
    const n = Number.parseInt(schemaRaw, 10);
    if (!Number.isFinite(n) || n < 1 || !/^\d+$/.test(schemaRaw)) {
      // Strict: typos and stray decimals/letters surface as errors rather
      // than silently defaulting to 1 (which was the old behavior and
      // hid bugs).
      errors.push(
        `Annotation \`servicebay.schema-version\` must be a positive integer; got "${schemaRaw}".`,
      );
    } else {
      schemaVersion = n;
    }
  }

  let tier: TemplateTier = 'feature';
  const tierRaw = readAnnotation(yamlText, 'servicebay.tier');
  if (tierRaw !== undefined) {
    if (KNOWN_TIERS.has(tierRaw as TemplateTier)) {
      tier = tierRaw as TemplateTier;
    } else {
      errors.push(
        `Annotation \`servicebay.tier\` must be one of ${[...KNOWN_TIERS].map(v => `"${v}"`).join(', ')}; ` +
        `got "${tierRaw}".`,
      );
    }
  }

  const dependencies: string[] = [];
  const depsRaw = readAnnotation(yamlText, 'servicebay.dependencies');
  if (depsRaw !== undefined) {
    for (const name of depsRaw.split(',').map(s => s.trim()).filter(Boolean)) {
      dependencies.push(name);
    }
  }

  // requiresApi (#588): per-API annotations of shape
  // `servicebay.requires-api.<name>: "<integer>"`. Returns undefined
  // when no such annotation exists so downstream code can short-circuit.
  let requiresApi: TemplateApiVersions | undefined;
  for (const api of Object.keys(SUPPORTED_API_VERSIONS) as TemplateApiName[]) {
    const raw = readAnnotation(yamlText, `servicebay.requires-api.${api}`);
    if (raw === undefined) continue;
    const n = Number.parseInt(raw, 10);
    if (!Number.isFinite(n) || n < 1 || !/^\d+$/.test(raw)) {
      errors.push(
        `Annotation \`servicebay.requires-api.${api}\` must be a positive integer; got "${raw}".`,
      );
      continue;
    }
    requiresApi = { ...(requiresApi ?? {}), [api]: n };
  }

  // readinessRaw (#613): pre-Mustache YAML body of the readiness probe list.
  // Validated structurally here — values may contain `{{VAR}}` placeholders
  // that the install runner substitutes before re-parsing at deploy time.
  const readinessRaw = readBlockScalarAnnotation(yamlText, 'servicebay.readiness');
  if (readinessRaw !== undefined) {
    // `permissive: true` — the raw template still has `{{VAR}}` placeholders
    // in fields like `port:` and `timeout:`. The install runner re-parses
    // strictly after Mustache substitution.
    const r = parseReadinessYaml(readinessRaw, { permissive: true });
    if (!r.ok) {
      for (const err of r.errors) {
        errors.push(`Annotation \`servicebay.readiness\`: ${err}`);
      }
    }
  }

  if (errors.length > 0) {
    return { ok: false, errors, warnings };
  }

  return {
    ok: true,
    manifest: {
      label: label!,
      tier,
      schemaVersion,
      dependencies,
      configMount,
      ports,
      requiresApi,
      readinessRaw,
    },
    warnings,
  };
}

/**
 * Compact helper for callers that only care whether a manifest exists.
 * Returns `null` when parsing fails. Use the full `parseTemplateManifest`
 * when you need the error list (registry sync, consistency tests).
 */
export function tryParseTemplateManifest(
  yamlText: string,
  ctx: ParseContext = {},
): TemplateManifest | null {
  const r = parseTemplateManifest(yamlText, ctx);
  return r.ok ? r.manifest : null;
}

/**
 * Permissive extraction — returns a `Partial<TemplateManifest>` with
 * whatever annotations are present, no validation. Used by the legacy
 * per-field wrappers (templateLabel.ts, templateTier.ts,
 * templateSchemaVersion.ts, stackInstall/dependencies.ts) so they can
 * keep operating on fragmentary YAML (e.g. tests passing only one
 * annotation) without tripping the strict required-fields check.
 *
 * New code should NOT use this — call `parseTemplateManifest` and
 * surface the error list.
 */
export function readManifestAnnotations(yamlText: string): Partial<TemplateManifest> {
  const out: Partial<TemplateManifest> = {};

  const label = readAnnotation(yamlText, 'servicebay.label');
  if (label !== undefined) out.label = label;

  const ports = readAnnotation(yamlText, 'servicebay.ports');
  if (ports !== undefined) out.ports = ports;

  const configMount = readAnnotation(yamlText, 'servicebay.config-mount');
  if (configMount !== undefined) out.configMount = configMount;

  const schemaRaw = readAnnotation(yamlText, 'servicebay.schema-version');
  if (schemaRaw !== undefined) {
    const n = Number.parseInt(schemaRaw, 10);
    if (Number.isFinite(n) && n >= 1 && /^\d+$/.test(schemaRaw)) {
      out.schemaVersion = n;
    }
  }

  const tierRaw = readAnnotation(yamlText, 'servicebay.tier');
  if (tierRaw !== undefined && KNOWN_TIERS.has(tierRaw as TemplateTier)) {
    out.tier = tierRaw as TemplateTier;
  }

  const depsRaw = readAnnotation(yamlText, 'servicebay.dependencies');
  if (depsRaw !== undefined) {
    out.dependencies = depsRaw.split(',').map(s => s.trim()).filter(Boolean);
  }

  let requiresApi: TemplateApiVersions | undefined;
  for (const api of Object.keys(SUPPORTED_API_VERSIONS) as TemplateApiName[]) {
    const raw = readAnnotation(yamlText, `servicebay.requires-api.${api}`);
    if (raw === undefined) continue;
    const n = Number.parseInt(raw, 10);
    if (Number.isFinite(n) && n >= 1 && /^\d+$/.test(raw)) {
      requiresApi = { ...(requiresApi ?? {}), [api]: n };
    }
  }
  if (requiresApi) out.requiresApi = requiresApi;

  const readinessRaw = readBlockScalarAnnotation(yamlText, 'servicebay.readiness');
  if (readinessRaw !== undefined) out.readinessRaw = readinessRaw;

  return out;
}
