import ServiceForm from '@/components/ServiceForm';
import PageHeader from '@/components/PageHeader';
import { getTemplateYaml } from '@/lib/registry';

export default async function CreatePage({ searchParams }: { searchParams: Promise<{ template?: string }> }) {
  const { template } = await searchParams;
  let initialData = undefined;

  if (template) {
    const yamlContent = await getTemplateYaml(template);
    if (yamlContent) {
        initialData = {
            name: template,
            yamlContent: yamlContent,
            yamlFileName: `${template}.yml`,
            kubeContent: '', // Will be generated by ServiceForm
        };
    }
  }

  return (
    <div className="h-full flex flex-col overflow-y-auto">
      <PageHeader title={template ? `Create Service from Template: ${template}` : "Create New Service"} />
      <div className="p-6">
        <ServiceForm initialData={initialData} />
      </div>
    </div>
  );
}
