/**
 * Template manifest — single source of truth for what `template.yml`
 * may contain and which fields are required (#585).
 *
 * Until this module existed, the same regex pattern was duplicated in
 * four files (templateLabel.ts, templateTier.ts, templateSchemaVersion.ts,
 * stackInstall/dependencies.ts) and twice more inline in registry.ts,
 * each parsing one annotation. Build-time tests then re-asserted some
 * (but not all) of those rules with hand-rolled regexes of their own.
 * Adding a field meant editing five files plus two docs.
 *
 * This module unifies the parsing into one function and one field-spec
 * table that drives both runtime validation and the autogenerated
 * field-reference section in docs/TEMPLATE_AUTHORING.md.
 *
 * Adding a field:
 *   1. extend TemplateManifest below
 *   2. add a `TEMPLATE_FIELDS` entry with required/default/description
 *   3. extend parseTemplateManifest with the field's parsing rule
 *   4. run `npm run gen-template-docs` to refresh the docs table
 *
 * No client/server split: the parser is pure (no fs / Node deps) and is
 * safe to import from React components.
 */

import { type TemplateApiVersions, type TemplateApiName, SUPPORTED_API_VERSIONS } from './apiVersions';
import { parseHealthcheckYaml } from '@/lib/health/serviceHealthcheck';

/** Recognized template tiers. `feature` is the implicit default. */
export type TemplateTier = 'infrastructure' | 'feature';
const KNOWN_TIERS: ReadonlySet<TemplateTier> = new Set(['infrastructure', 'feature']);

/** Parsed template metadata. Stable shape — both runtime + tests rely on it. */
export interface TemplateManifest {
  /** `metadata.annotations['servicebay.label']` — friendly UI label. Required. */
  label: string;
  /**
   * `metadata.annotations['servicebay.tier']`. `feature` is the implicit
   * default — anything not in KNOWN_TIERS is an error.
   */
  tier: TemplateTier;
  /**
   * `metadata.annotations['servicebay.schema-version']`. Positive integer.
   * Defaults to 1 when the annotation is missing.
   */
  schemaVersion: number;
  /**
   * `metadata.annotations['servicebay.min-upgradable-schema-version']` (#2727).
   * The oldest installed schema-version this template can still be upgraded
   * FROM. Defaults to 1.
   *
   * `selectMigrationChain` walks one hop at a time and refuses the deploy on
   * a hop with no script, so a template whose `migrations/` directory has a
   * hole is simply not upgradable from below that hole — media has no
   * `v2-to-v3.py`, home-assistant has no `v2-to-v3` / `v4-to-v5` / `v5-to-v6`.
   * Before #2727 that fact was undeclared: the box found out mid-job, via a
   * `missing-step` abort, and the scripts sitting below the hole could never
   * run at all.
   *
   * Declaring the floor makes it a contract instead of an accident. The build-
   * time consistency test pins that the chain from this version up to
   * `schemaVersion` is unbroken AND that no migration script sits below it,
   * and `install/runner.ts` refuses a box recorded below it up front, naming
   * the template, the installed version and the minimum.
   *
   * Must satisfy `1 <= minUpgradableSchemaVersion <= schemaVersion`.
   */
  minUpgradableSchemaVersion: number;
  /**
   * `metadata.annotations['servicebay.dependencies']` — comma-separated
   * template names this template needs installed first. Empty array when
   * missing.
   */
  dependencies: string[];
  /**
   * `metadata.annotations['servicebay.config-mount']` — container mountPath
   * the wizard should write companion `*.mustache` files into. Required
   * only when the template ships `*.mustache` files (caller signals via
   * ParseContext.hasMustacheConfigs).
   */
  configMount?: string;
  /**
   * `metadata.annotations['servicebay.seed-only-configs']` — companion config
   * filenames ServiceBay may write ONLY when they do not already exist on the
   * box (#2590). Empty array when the annotation is missing, i.e. the default
   * stays "re-render this file on every deploy".
   *
   * This is the declaration side of ADR 0004 ("installs are non-destructive")
   * for companion config files: a file the *application* owns after first
   * install — Home Assistant's `automations.yaml` is rewritten by HA's own
   * editor — must never be re-seeded over. See `writeExtraConfigFiles` in
   * `services/serviceLifecycle.ts` for the enforcement side.
   */
  seedOnlyConfigs: string[];
  /**
   * `metadata.annotations['servicebay.ports']` — comma-separated `port/proto`
   * list (e.g. `"8080/tcp,8443/tcp"`). Recommended; no validation beyond
   * "is a string" today.
   */
  ports?: string;
  /**
   * `metadata.annotations['servicebay.requires-api.<name>']` (#588).
   * Each declared key is the version of a ServiceBay-internal `/api/system/<name>/*`
   * surface the template's `post-deploy.py` calls. Core refuses to invoke
   * `post-deploy.py` if the template requests a version this core can't satisfy.
   * Empty / missing = template makes no such calls.
   */
  requiresApi?: TemplateApiVersions;
  /**
   * `metadata.annotations['servicebay.healthcheck']` (#626) — raw YAML
   * body of the continuous health probe. Stored unparsed because the
   * parser runs twice:
   *   1. At lint/test time on the pre-Mustache template — `{{VAR}}`
   *      placeholders survive as opaque strings.
   *   2. At runtime in the bootstrap, on the Mustache-rendered body,
   *      to get concrete probe values.
   * Phase 3C (#628) replaced the install-time `servicebay.readiness`
   * annotation with this single signal — settleWait now reads
   * `twin.health.ready` for install gating, same source the
   * continuous-monitoring readers use.
   */
  healthcheckRaw?: string;
}

/** Context the caller can pass to enable conditional rules. */
export interface ParseContext {
  /** True if the template directory contains `*.mustache` companion config
   *  files. When set, `servicebay.config-mount` becomes required — without
   *  the annotation the resolver falls back to a `/config`-suffix heuristic
   *  that silently picks the wrong mount in multi-volume pods. */
  hasMustacheConfigs?: boolean;
  /** Deployed filenames of the `*.mustache` companion configs the template
   *  directory ships (i.e. with the `.mustache` suffix stripped). When
   *  provided, every entry of `servicebay.seed-only-configs` must name one of
   *  them — a typo'd or stale entry would otherwise silently protect nothing,
   *  which is the failure mode the annotation exists to prevent. */
  mustacheConfigFilenames?: string[];
}

export type ParseResult =
  | { ok: true; manifest: TemplateManifest; warnings: string[] }
  | { ok: false; errors: string[]; warnings: string[] };

/**
 * Field-spec table. Single source of truth for both parser behavior and
 * the autogenerated docs table. Order is the order entries appear in the
 * generated docs (most-important first).
 */
export interface TemplateFieldSpec {
  /** Annotation key inside `metadata.annotations`. */
  annotation: string;
  /** Manifest field name. */
  field: keyof TemplateManifest;
  /** `true` always required; `'if-mustache-configs'` required iff the
   *  template ships `*.mustache` files; `false` optional. */
  required: true | false | 'if-mustache-configs';
  /** Default applied when annotation is missing (and field is not required). */
  default?: string | number | string[];
  /** Enum of allowed values, if any. */
  validValues?: readonly string[];
  /** One-line description for the docs table. */
  description: string;
}

export const TEMPLATE_FIELDS: readonly TemplateFieldSpec[] = [
  {
    annotation: 'servicebay.label',
    field: 'label',
    required: true,
    description:
      'Friendly UI label shown in the wizard\'s configure step (e.g. `"Vaultwarden (Passwords)"`). ' +
      'Without it the section header falls back to the raw template name.',
  },
  {
    annotation: 'servicebay.ports',
    field: 'ports',
    required: false,
    description:
      'Comma-separated `port/proto` list (e.g. `"8080/tcp,8443/tcp"`). ' +
      'Drives gateway probes + the network graph.',
  },
  {
    annotation: 'servicebay.config-mount',
    field: 'configMount',
    required: 'if-mustache-configs',
    description:
      'Container mountPath that companion `*.mustache` files should land in. ' +
      'Avoids the `/config`-suffix heuristic picking the wrong volume in multi-container pods.',
  },
  {
    annotation: 'servicebay.seed-only-configs',
    field: 'seedOnlyConfigs',
    required: false,
    default: [],
    description:
      'Comma-separated companion config filenames (e.g. `"automations.yaml,scenes.yaml,scripts.yaml"`) that ' +
      'ServiceBay writes **only when they are absent** on the box. Use it for any `*.mustache` file whose ' +
      'real owner after first install is the application or the operator — an app that rewrites the file from ' +
      'its own UI, or a file the operator edits by hand. Without the annotation a deploy re-renders the file ' +
      'every time, which overwrites that content (#2590). Each name must match a `*.mustache` file the ' +
      'template ships, minus the suffix.',
  },
  {
    annotation: 'servicebay.schema-version',
    field: 'schemaVersion',
    required: false,
    default: 1,
    description:
      'Bump when the pod structure or variable shape changes in a way operators need to be aware of ' +
      '(containers extracted, variables renamed, data paths moved). Plain image-tag bumps don\'t need ' +
      'this — Quadlet\'s `AutoUpdate=registry` handles those silently. Each bump should ship a ' +
      '`CHANGELOG.md` section + (if data needs to move) a `migrations/v{N-1}-to-v{N}.py` script. See #352.',
  },
  {
    annotation: 'servicebay.min-upgradable-schema-version',
    field: 'minUpgradableSchemaVersion',
    required: false,
    default: 1,
    description:
      'Oldest installed schema-version this template can still be upgraded **from**. Raise it when the '
      + '`migrations/` chain has a hole below the current version and filling it would mean guessing what '
      + 'moved on disk years ago — the hole already makes the template undeployable for those boxes, this '
      + 'annotation makes that a declared contract instead of a mid-job `missing-step` abort. The install '
      + 'runner refuses a box recorded below it up front, naming template + installed + minimum version, and '
      + 'a build-time test pins that the chain from here to `servicebay.schema-version` is unbroken and that '
      + 'no unreachable migration script is left below it. Must be `>= 1` and `<= servicebay.schema-version`. '
      + 'See #2727.',
  },
  {
    annotation: 'servicebay.tier',
    field: 'tier',
    required: false,
    default: 'feature',
    validValues: ['infrastructure', 'feature'],
    description:
      '`"infrastructure"` for platform templates that the wizard auto-includes (DNS / proxy / SSO) and ' +
      'pins checked; everything else defaults to `"feature"` and starts unchecked. Stacks don\'t carry ' +
      'this annotation.',
  },
  {
    annotation: 'servicebay.dependencies',
    field: 'dependencies',
    required: false,
    default: [],
    description:
      'Comma-separated list of template names that must install before this one. Drives three things ' +
      'in the wizard: (1) the red **`requires X`** badge under the template name; (2) auto-checking ' +
      'those templates when the operator checks this one; (3) the uncheck-guard that prompts before ' +
      'removing a template another selected template needs. The install loop then topo-sorts the ' +
      'deploy order so deps land first. Example: `servicebay.dependencies: "nginx,auth"`.',
  },
  {
    annotation: 'servicebay.requires-api.<name>',
    field: 'requiresApi',
    required: false,
    description:
      'Per-API version the template\'s `post-deploy.py` calls. Declare one annotation per API name (`lldap`, ' +
      '`authelia`, `portal`), value is a positive integer. Core refuses to invoke `post-deploy.py` if any ' +
      'requested version exceeds what this ServiceBay ships (see `packages/backend/src/lib/template/apiVersions.ts`). ' +
      'Use this on any template whose post-deploy calls `/api/system/<name>/*` (#588).',
  },
  {
    annotation: 'servicebay.healthcheck',
    field: 'healthcheckRaw',
    required: false,
    description:
      'YAML block scalar declaring a continuous health probe ServiceBay polls on the configured interval (#626). ' +
      'Shape: `{kind?: http|tcp, url|host+port, interval: 30s, timeout: 5s, startup_timeout: 5m}`. The endpoint ' +
      'should return `{ready, degraded?, deps?, message?}`. Result lands on `twin.services[].health` and is the ' +
      'single source of truth for install gating (`settleWait`), diagnose readers, and the core-health banner. ' +
      'Phase 3C (#628) replaced the install-time `servicebay.readiness` annotation with this single signal.',
  },
] as const;

/**
 * Pull a multi-line YAML block scalar (`key: |` or `key: >`) out of raw
 * template YAML. Indentation-anchored: captures every subsequent line
 * indented strictly more than the key line, stops at the first line that
 * dedents back to (or past) the key. Returns the block body with the
 * leading per-line indentation stripped — i.e. the raw YAML you'd feed
 * into a follow-up `yaml.load`.
 */
function readBlockScalarAnnotation(yamlText: string, annotation: string): string | undefined {
  const escaped = annotation.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const headerRe = new RegExp(`^(\\s+)${escaped}:\\s*([|>])[+-]?\\s*$`, 'm');
  const header = headerRe.exec(yamlText);
  if (!header) return undefined;
  const keyIndent = header[1].length;
  const afterHeader = yamlText.slice(header.index + header[0].length);
  const lines = afterHeader.split('\n');
  // First line after the header is the start of the block; consume lines
  // indented strictly deeper than the key. A blank line is part of the
  // block if the next non-blank line is still indented.
  const blockLines: string[] = [];
  let blockIndent: number | null = null;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === '') { blockLines.push(''); continue; }
    const indent = line.length - line.trimStart().length;
    if (indent <= keyIndent) break;
    if (blockIndent === null) blockIndent = indent;
    blockLines.push(line.slice(Math.min(indent, blockIndent)));
  }
  // Trim trailing blank lines that aren't part of any indented content.
  while (blockLines.length > 0 && blockLines[blockLines.length - 1].trim() === '') {
    blockLines.pop();
  }
  if (blockLines.length === 0) return undefined;
  return blockLines.join('\n') + '\n';
}

/**
 * Pull a single annotation value out of raw YAML text. Regex-based on
 * purpose: this function runs against pre-mustache-substitution YAML
 * (the wizard collects variables before render), and our templates
 * contain `{{PLACEHOLDER}}` strings that pass js-yaml's parser
 * incidentally — we don't want to depend on that. Annotation values
 * themselves are always literal strings in our templates.
 *
 * Matches `key: "..."`, `key: '...'`, or `key: bare value` (until end
 * of line). Anchored to an annotation-style indented line so it doesn't
 * latch onto references inside multi-line scalars or comments.
 */
function readAnnotation(yamlText: string, annotation: string): string | undefined {
  // Escape regex metacharacters in the annotation key (the `.` in
  // `servicebay.label` would otherwise match anything).
  const escaped = annotation.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(
    `^\\s+${escaped}:\\s*(?:"([^"]*)"|'([^']*)'|([^\\n#]+?))\\s*$`,
    'm',
  );
  const m = re.exec(yamlText);
  if (!m) return undefined;
  const raw = (m[1] ?? m[2] ?? m[3] ?? '').trim();
  return raw === '' ? undefined : raw;
}

/**
 * Validate and extract template metadata fields from parsed annotations.
 */
function validateTemplateMetadata(
  yamlText: string,
  ctx: ParseContext,
): {
  label: string | undefined;
  ports: string | undefined;
  configMount: string | undefined;
  seedOnlyConfigs: string[];
  schemaVersion: number;
  minUpgradableSchemaVersion: number;
  tier: TemplateTier;
  dependencies: string[];
  requiresApi: TemplateApiVersions | undefined;
  errors: string[];
} {
  const errors: string[] = [];

  const label = readAnnotation(yamlText, 'servicebay.label');
  if (label === undefined) {
    errors.push(
      'Missing required annotation `servicebay.label`. Add it under `metadata.annotations` ' +
      'with a friendly display name (e.g. `servicebay.label: "Vaultwarden (Passwords)"`).',
    );
  }

  const ports = readAnnotation(yamlText, 'servicebay.ports');

  const configMount = readAnnotation(yamlText, 'servicebay.config-mount');
  if (ctx.hasMustacheConfigs && !configMount) {
    errors.push(
      'Template ships *.mustache config files but has no `servicebay.config-mount` annotation. ' +
      'Without it the resolver falls back to a `/config`-suffix heuristic that silently picks the ' +
      'wrong mount in multi-volume pods. Add `servicebay.config-mount: "<container mountPath>"` ' +
      'pointing at the volume the configs should land in.',
    );
  }

  // #2590 — the files a deploy is only allowed to SEED, never to overwrite.
  // Two rules, both errors rather than warnings: an entry that names nothing
  // the template ships protects nothing, and an entry with a path separator
  // would be compared against a basename and therefore also never match. Both
  // shapes fail silently at runtime (the file is simply re-rendered over the
  // operator's content), so they have to fail loudly here instead.
  const seedOnlyConfigs: string[] = [];
  const seedOnlyRaw = readAnnotation(yamlText, 'servicebay.seed-only-configs');
  if (seedOnlyRaw !== undefined) {
    const shipped = ctx.mustacheConfigFilenames;
    for (const entry of seedOnlyRaw.split(',').map(s => s.trim()).filter(Boolean)) {
      if (entry.includes('/') || entry === '.' || entry === '..') {
        errors.push(
          `Annotation \`servicebay.seed-only-configs\` entry "${entry}" must be a bare filename ` +
          `(no path separators) — it is matched against the config file's own name.`,
        );
        continue;
      }
      if (shipped && !shipped.includes(entry)) {
        errors.push(
          `Annotation \`servicebay.seed-only-configs\` names "${entry}", but the template ships no ` +
          `\`${entry}.mustache\` config file${shipped.length > 0 ? ` (it ships: ${shipped.join(', ')})` : ''}. ` +
          `An entry that matches nothing protects nothing — fix the name or drop it.`,
        );
        continue;
      }
      seedOnlyConfigs.push(entry);
    }
  }

  let schemaVersion = 1;
  const schemaRaw = readAnnotation(yamlText, 'servicebay.schema-version');
  if (schemaRaw !== undefined) {
    const n = Number.parseInt(schemaRaw, 10);
    if (!Number.isFinite(n) || n < 1 || !/^\d+$/.test(schemaRaw)) {
      errors.push(
        `Annotation \`servicebay.schema-version\` must be a positive integer; got "${schemaRaw}".`,
      );
    } else {
      schemaVersion = n;
    }
  }

  // #2727 — the oldest version this template can still be upgraded from.
  // Both bounds are errors, not warnings: a floor above the current
  // schema-version would refuse EVERY upgrade including the current one, and
  // a non-integer would silently fall back to 1 and re-open the mid-job
  // `missing-step` abort this annotation exists to replace.
  let minUpgradableSchemaVersion = 1;
  const minUpgradableRaw = readAnnotation(yamlText, 'servicebay.min-upgradable-schema-version');
  if (minUpgradableRaw !== undefined) {
    const n = Number.parseInt(minUpgradableRaw, 10);
    if (!Number.isFinite(n) || n < 1 || !/^\d+$/.test(minUpgradableRaw)) {
      errors.push(
        'Annotation `servicebay.min-upgradable-schema-version` must be a positive integer; '
        + `got "${minUpgradableRaw}".`,
      );
    } else if (n > schemaVersion) {
      errors.push(
        `Annotation \`servicebay.min-upgradable-schema-version\` is ${n}, above `
        + `\`servicebay.schema-version\` (${schemaVersion}). The floor is the oldest version an upgrade may `
        + 'start from, so a floor above the current version refuses every deploy on every box.',
      );
    } else {
      minUpgradableSchemaVersion = n;
    }
  }

  let tier: TemplateTier = 'feature';
  const tierRaw = readAnnotation(yamlText, 'servicebay.tier');
  if (tierRaw !== undefined) {
    if (KNOWN_TIERS.has(tierRaw as TemplateTier)) {
      tier = tierRaw as TemplateTier;
    } else {
      errors.push(
        `Annotation \`servicebay.tier\` must be one of ${[...KNOWN_TIERS].map(v => `"${v}"`).join(', ')}; ` +
        `got "${tierRaw}".`,
      );
    }
  }

  const dependencies: string[] = [];
  const depsRaw = readAnnotation(yamlText, 'servicebay.dependencies');
  if (depsRaw !== undefined) {
    for (const name of depsRaw.split(',').map(s => s.trim()).filter(Boolean)) {
      dependencies.push(name);
    }
  }

  let requiresApi: TemplateApiVersions | undefined;
  for (const api of Object.keys(SUPPORTED_API_VERSIONS) as TemplateApiName[]) {
    const raw = readAnnotation(yamlText, `servicebay.requires-api.${api}`);
    if (raw === undefined) continue;
    const n = Number.parseInt(raw, 10);
    if (!Number.isFinite(n) || n < 1 || !/^\d+$/.test(raw)) {
      errors.push(
        `Annotation \`servicebay.requires-api.${api}\` must be a positive integer; got "${raw}".`,
      );
      continue;
    }
    requiresApi = { ...(requiresApi ?? {}), [api]: n };
  }

  return {
    label,
    ports,
    configMount,
    seedOnlyConfigs,
    schemaVersion,
    minUpgradableSchemaVersion,
    tier,
    dependencies,
    requiresApi,
    errors,
  };
}

/**
 * Parse a template.yml's manifest annotations. Pure function — caller
 * passes the YAML text plus optional context flags. Returns either a
 * complete manifest or a list of human-readable errors.
 */
export function parseTemplateManifest(
  yamlText: string,
  ctx: ParseContext = {},
): ParseResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  const meta = validateTemplateMetadata(yamlText, ctx);
  errors.push(...meta.errors);

  // healthcheckRaw (#626): pre-Mustache YAML body of the continuous health
  // probe. Pre-Mustache `{{VAR}}` placeholders in
  // `url` / `port` survive lint-time and resolve at runtime.
  const healthcheckRaw = readBlockScalarAnnotation(yamlText, 'servicebay.healthcheck');
  if (healthcheckRaw !== undefined) {
    const r = parseHealthcheckYaml(healthcheckRaw, { permissive: true });
    if (!r.ok) {
      for (const err of r.errors) {
        errors.push(`Annotation \`servicebay.healthcheck\`: ${err}`);
      }
    }
  }

  if (errors.length > 0) {
    return { ok: false, errors, warnings };
  }

  return {
    ok: true,
    manifest: {
      label: meta.label!,
      tier: meta.tier,
      schemaVersion: meta.schemaVersion,
      minUpgradableSchemaVersion: meta.minUpgradableSchemaVersion,
      dependencies: meta.dependencies,
      configMount: meta.configMount,
      seedOnlyConfigs: meta.seedOnlyConfigs,
      ports: meta.ports,
      requiresApi: meta.requiresApi,
      healthcheckRaw,
    },
    warnings,
  };
}

/**
 * Compact helper for callers that only care whether a manifest exists.
 * Returns `null` when parsing fails. Use the full `parseTemplateManifest`
 * when you need the error list (registry sync, consistency tests).
 */
export function tryParseTemplateManifest(
  yamlText: string,
  ctx: ParseContext = {},
): TemplateManifest | null {
  const r = parseTemplateManifest(yamlText, ctx);
  return r.ok ? r.manifest : null;
}

/**
 * Read an annotation that must be a positive integer, permissively:
 * `undefined` for both "absent" and "present but not a positive integer".
 * The strict counterpart lives in `validateTemplateMetadata`, which turns the
 * second case into an error.
 */
function readPositiveIntAnnotation(yamlText: string, annotation: string): number | undefined {
  const raw = readAnnotation(yamlText, annotation);
  if (raw === undefined) return undefined;
  const n = Number.parseInt(raw, 10);
  return Number.isFinite(n) && n >= 1 && /^\d+$/.test(raw) ? n : undefined;
}

/**
 * Resolve optional annotations and apply permissive defaults.
 */
function resolveAnnotationDefaults(yamlText: string): Partial<TemplateManifest> {
  const out: Partial<TemplateManifest> = {};

  const label = readAnnotation(yamlText, 'servicebay.label');
  if (label !== undefined) out.label = label;

  const ports = readAnnotation(yamlText, 'servicebay.ports');
  if (ports !== undefined) out.ports = ports;

  const configMount = readAnnotation(yamlText, 'servicebay.config-mount');
  if (configMount !== undefined) out.configMount = configMount;

  const schemaVersion = readPositiveIntAnnotation(yamlText, 'servicebay.schema-version');
  if (schemaVersion !== undefined) out.schemaVersion = schemaVersion;

  // #2727 — permissive read of the upgrade floor. The `<= schemaVersion`
  // bound is NOT checked here: this path exists for fragmentary YAML that may
  // carry the floor without the version. `parseTemplateManifest` is the strict
  // path that rejects an out-of-range floor.
  const floor = readPositiveIntAnnotation(yamlText, 'servicebay.min-upgradable-schema-version');
  if (floor !== undefined) out.minUpgradableSchemaVersion = floor;

  const tierRaw = readAnnotation(yamlText, 'servicebay.tier');
  if (tierRaw !== undefined && KNOWN_TIERS.has(tierRaw as TemplateTier)) {
    out.tier = tierRaw as TemplateTier;
  }

  const depsRaw = readAnnotation(yamlText, 'servicebay.dependencies');
  if (depsRaw !== undefined) {
    out.dependencies = depsRaw.split(',').map(s => s.trim()).filter(Boolean);
  }

  // #2590 — permissive read of the seed-only list. Entries carrying a path
  // separator are dropped rather than kept: they can never match a basename,
  // and the runtime consumer must not be handed something path-shaped.
  const seedOnlyRaw = readAnnotation(yamlText, 'servicebay.seed-only-configs');
  if (seedOnlyRaw !== undefined) {
    out.seedOnlyConfigs = seedOnlyRaw
      .split(',')
      .map(s => s.trim())
      .filter(s => s !== '' && !s.includes('/') && s !== '.' && s !== '..');
  }

  let requiresApi: TemplateApiVersions | undefined;
  for (const api of Object.keys(SUPPORTED_API_VERSIONS) as TemplateApiName[]) {
    const n = readPositiveIntAnnotation(yamlText, `servicebay.requires-api.${api}`);
    if (n !== undefined) requiresApi = { ...(requiresApi ?? {}), [api]: n };
  }
  if (requiresApi) out.requiresApi = requiresApi;

  const healthcheckRaw = readBlockScalarAnnotation(yamlText, 'servicebay.healthcheck');
  if (healthcheckRaw !== undefined) out.healthcheckRaw = healthcheckRaw;

  return out;
}

/**
 * Permissive extraction — returns a `Partial<TemplateManifest>` with
 * whatever annotations are present, no validation. Used by the legacy
 * per-field wrappers (templateLabel.ts, templateTier.ts,
 * templateSchemaVersion.ts, stackInstall/dependencies.ts) so they can
 * keep operating on fragmentary YAML (e.g. tests passing only one
 * annotation) without tripping the strict required-fields check.
 *
 * New code should NOT use this — call `parseTemplateManifest` and
 * surface the error list.
 */
export function readManifestAnnotations(yamlText: string): Partial<TemplateManifest> {
  return resolveAnnotationDefaults(yamlText);
}
